# **----One Hot Encoding Sklearn**

In [ ]:
import pandas as pd
import numpy as np
from sklearn.ensemble import RandomForestClassifier

from sklearn.model_selection import train_test_split

In [ ]:
df = pd.read_csv("dosya.csv")

In [ ]:
df.head(3)

RowNumber  CustomerId   Surname  ...  IsActiveMember EstimatedSalary Exited
0          1    15634602  Hargrave  ...               1       101348.88      1
1          2    15647311      Hill  ...               1       112542.58      0
2          3    15619304      Onio  ...               0       113931.57      1

[3 rows x 14 columns]

In [ ]:
df = df.drop(columns=["RowNumber","CustomerId","Surname"])

In [ ]:
df.head(3)

CreditScore Geography  Gender  ...  IsActiveMember  EstimatedSalary  Exited
0          619    France  Female  ...               1        101348.88       1
1          608     Spain  Female  ...               1        112542.58       0
2          502    France  Female  ...               0        113931.57       1

[3 rows x 11 columns]

In [ ]:
df = pd.get_dummies(df, columns=["Geography","Gender"] , drop_first=True)

In [ ]:
df.head(3)

CreditScore  Age  Tenure  ...  Geography_Germany  Geography_Spain  Gender_Male
0          619   42       2  ...              False            False        False
1          608   41       1  ...              False             True        False
2          502   42       8  ...              False            False        False

[3 rows x 12 columns]

In [ ]:
y = df["Exited"]
x = df.drop("Exited" , axis = 1)

In [ ]:
x_train , x_test , y_train , y_test = train_test_split(x,y,random_state = 61 , train_size = 0.7)

In [ ]:
rf = RandomForestClassifier()
model = rf.fit(x_train , y_train)
model.score(x_test , y_test)

0.864

In [ ]:
# DATA SET ÇALIŞSADA ORTADA PROBLEM VAR
# Geography_Germany ,Geography_Spain GİBİ SÜTUNLAR 100 lerce olsa çok sorun olurdu

In [ ]:
from sklearn.preprocessing import OneHotEncoder

In [ ]:
teams = ["Real Madrid", "Barcelona", "Manchester United", "Manchester City", "Liverpool",
         "Chelsea", "Arsenal", "Tottenham Hotspur", "Bayern Münih", "Borussia Dortmund",
         "Paris Saint-Germain", "Olympique Lyon", "Juventus", "AC Milan", "Inter Milan",
         "AS Roma", "Napoli", "Ajax", "Fenerbahçe", "Galatasaray", "Beşiktaş",
         "Trabzonspor", "Porto", "Benfica", "Sporting Lisbon"]

In [ ]:
df = pd.DataFrame()
df["Takım"] = teams
df.head(3)

Takım
0        Real Madrid
1          Barcelona
2  Manchester United

In [ ]:
ohe = OneHotEncoder()
x = ohe.fit_transform(df[["Takım"]])

In [ ]:
x.toarray()

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.,
        0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 

In [ ]:


#.predict komutunu kullanırken 24 tane takıma false yazıp real madride 1 yazmaktansa  elimiz ile bu komut ile yazıcağımız şeyi alabiliriz


ohe.transform([["Real Madrid"]]).toarray()

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(


array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 1., 0., 0., 0.]])

In [ ]:
df = pd.read_csv("dosya.csv")

In [ ]:
df = df.drop(columns=["RowNumber","CustomerId","Surname"])
df.head(3)

CreditScore Geography  Gender  ...  IsActiveMember  EstimatedSalary  Exited
0          619    France  Female  ...               1        101348.88       1
1          608     Spain  Female  ...               1        112542.58       0
2          502    France  Female  ...               0        113931.57       1

[3 rows x 11 columns]

In [ ]:
ohe = OneHotEncoder()
xd = ohe.fit_transform(df[["Geography" , "Gender"]]).toarray()

In [ ]:
xd

array([[1., 0., 0., 1., 0.],
       [0., 0., 1., 1., 0.],
       [1., 0., 0., 1., 0.],
       ...,
       [1., 0., 0., 1., 0.],
       [0., 1., 0., 0., 1.],
       [1., 0., 0., 1., 0.]])

In [ ]:
ohe.get_feature_names_out()

array(['Geography_France', 'Geography_Germany', 'Geography_Spain',
       'Gender_Female', 'Gender_Male'], dtype=object)

In [ ]:
xd = pd.DataFrame(xd)

In [ ]:
xd.columns = ohe.get_feature_names_out()

In [ ]:
xd

Geography_France  Geography_Germany  ...  Gender_Female  Gender_Male
0                  1.0                0.0  ...            1.0          0.0
1                  0.0                0.0  ...            1.0          0.0
2                  1.0                0.0  ...            1.0          0.0
3                  1.0                0.0  ...            1.0          0.0
4                  0.0                0.0  ...            1.0          0.0
...                ...                ...  ...            ...          ...
9995               1.0                0.0  ...            0.0          1.0
9996               1.0                0.0  ...            0.0          1.0
9997               1.0                0.0  ...            1.0          0.0
9998               0.0                1.0  ...            0.0          1.0
9999               1.0                0.0  ...            1.0          0.0

[10000 rows x 5 columns]

In [ ]:
df = df.drop(columns=["Geography" , "Gender"])
df.head(3)

CreditScore  Age  Tenure  ...  IsActiveMember  EstimatedSalary  Exited
0          619   42       2  ...               1        101348.88       1
1          608   41       1  ...               1        112542.58       0
2          502   42       8  ...               0        113931.57       1

[3 rows x 9 columns]

In [ ]:
df[xd.columns] = xd

In [ ]:
df.head(3)

CreditScore  Age  Tenure  ...  Geography_Spain  Gender_Female  Gender_Male
0          619   42       2  ...              0.0            1.0          0.0
1          608   41       1  ...              1.0            1.0          0.0
2          502   42       8  ...              0.0            1.0          0.0

[3 rows x 14 columns]