# **----LabelEncoder**

In [ ]:
# kategorisel verileri numeric verilere çeviriyor

# ["bjk" , "gs" , "bjk" , "fb"] , [0,1,0,2]

# dummy komutu bağımlı değişkenlerde( y = ax + b deki Y) kullanılması zor

In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder

In [3]:
df = pd.read_csv("tur.csv")
df.head(3)

Year  Tour_No            Winner   Country               Team  \
0  2023      110  Jonas Vingegaard   Denmark   Team Jumbo Visma   
1  2022      109  Jonas Vingegaard   Denmark   Team Jumbo Visma   
2  2021      108     Tadej Pogacar  Slovenia  UAE Team Emirates   

  Tour_overall_length_(km)  age   BMI  weight_(Kg)  height_(m)  \
0                     3406   25  19.6         60.0    1.749636   
1                     3328   25  19.6         60.0    1.749636   
2                     3383   22  21.3         66.0    1.760282   

  rider_type_(PPS) close_rider_type_(PPS)  
0          climber                    NaN  
1          climber                    NaN  
2          climber                    NaN

In [4]:
df["Team"].unique()

array(['Team Jumbo Visma', 'UAE Team Emirates', 'Team Ineos ', 'Team Sky',
       'Astana Pro Team', 'BMC Racing Team', 'Team Saxo Bank', 'Astana',
       'Team CSC Saxo Bank', 'Discovery Channel', "Caisse d'Epargne",
       'US Postal Service', 'Mercatone Uno', 'Telekom', 'Banesto',
       'Z Tomasso', 'ADR', 'Reynolds', 'Carrera', 'La Vie Claire',
       'Renault', 'TI Raleigh', 'Peugeot', 'Gitane', 'Molteni', 'Bic',
       'Faemino', 'Faema', 'Holland', 'France', 'Ford', 'Salvarini',
       'St-Raphael', 'Italy', 'Spain', 'Holland Luxembourg',
       'Nord Est Centre', 'Switzerland', 'Ouest', 'Belgium', 'Alcyon',
       'Automoto', 'Cycles Peugeot', 'La Sportive', 'Alycon', 'Cycles JC',
       'La Francaise'], dtype=object)

In [6]:
le = LabelEncoder()
le.fit(df["Team"])

LabelEncoder()

In [7]:
df["Team"] = le.transform(df["Team"])

array([40, 40, 44, 44, 39, 42, 42, 42, 42,  4, 42, 42,  6, 41,  3, 38, 14,
       10, 14, 45, 45, 45, 45, 45, 45, 26, 43, 43,  7,  7,  7,  7,  7, 46,
        0, 32, 11, 25, 25, 31, 31, 31, 31, 37, 31, 31, 30, 19, 30, 27,  9,
       27, 27, 16, 15, 20, 18, 17, 33, 35, 35, 35, 18, 22, 34, 21, 18, 28,
       18, 18, 18, 22, 36, 36, 22, 22, 29,  8, 22, 18,  8,  8, 18, 18, 18,
       18, 18,  1,  1,  1,  5,  5,  5,  5, 13, 24, 24, 24, 13, 13,  2,  2,
        2,  2, 13, 13, 13, 13, 12, 23])

In [8]:
le.classes_

array(['ADR', 'Alcyon', 'Alycon', 'Astana', 'Astana Pro Team', 'Automoto',
       'BMC Racing Team', 'Banesto', 'Belgium', 'Bic', "Caisse d'Epargne",
       'Carrera', 'Cycles JC', 'Cycles Peugeot', 'Discovery Channel',
       'Faema', 'Faemino', 'Ford', 'France', 'Gitane', 'Holland',
       'Holland Luxembourg', 'Italy', 'La Francaise', 'La Sportive',
       'La Vie Claire', 'Mercatone Uno', 'Molteni', 'Nord Est Centre',
       'Ouest', 'Peugeot', 'Renault', 'Reynolds', 'Salvarini', 'Spain',
       'St-Raphael', 'Switzerland', 'TI Raleigh', 'Team CSC Saxo Bank',
       'Team Ineos ', 'Team Jumbo Visma', 'Team Saxo Bank', 'Team Sky',
       'Telekom', 'UAE Team Emirates', 'US Postal Service', 'Z Tomasso'],
      dtype=object)

In [9]:
# EN KOLAY ÇEVİRME YOLU
le2=LabelEncoder()
le2.fit_transform(df["Team"])

# KATEGORİK OLAN VERİLERİ NUMERİĞE ÇEVİRMENİN KOLAY YOLU

array([40, 40, 44, 44, 39, 42, 42, 42, 42,  4, 42, 42,  6, 41,  3, 38, 14,
       10, 14, 45, 45, 45, 45, 45, 45, 26, 43, 43,  7,  7,  7,  7,  7, 46,
        0, 32, 11, 25, 25, 31, 31, 31, 31, 37, 31, 31, 30, 19, 30, 27,  9,
       27, 27, 16, 15, 20, 18, 17, 33, 35, 35, 35, 18, 22, 34, 21, 18, 28,
       18, 18, 18, 22, 36, 36, 22, 22, 29,  8, 22, 18,  8,  8, 18, 18, 18,
       18, 18,  1,  1,  1,  5,  5,  5,  5, 13, 24, 24, 24, 13, 13,  2,  2,
        2,  2, 13, 13, 13, 13, 12, 23])

# **----- Count Vectorizer - NLP -**

In [13]:
import pandas as pd
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer

In [41]:
df = pd.DataFrame()

In [42]:
df["cumleler"] = ["ali bak" , "ali ata bak" ,"bak ali bak" , "ali güzel ata bak" ,"ışık ılık süt iç" , "ışık süt iç" , "iç ışık iç"]

In [43]:
cv = CountVectorizer(max_features = 4 ) ##### max features mesela 4 e eşit olsa genel olarak listedeki en önemli 4 kelimeyi alır

# sonrada eklenene ışık süt iç sayesinde ışık önemli bir kelime oldu

# sonradan eklenen iç ışık iç ile birlkite önemli kelimeler değiştir

In [44]:
a = cv.fit_transform(df["cumleler"])

In [45]:
a.toarray()

array([[1, 1, 0, 0],
       [1, 1, 0, 0],
       [1, 2, 0, 0],
       [1, 1, 0, 0],
       [0, 0, 1, 1],
       [0, 0, 1, 1],
       [0, 0, 2, 1]])

In [46]:
cv.get_feature_names_out()

array(['ali', 'bak', 'iç', 'ışık'], dtype=object)

In [ ]:
# stop words

# cümlelerde çok kullanılan ama kategorlileştirdiğimiz şeylerde işimize yaramayanlardır

# ( mesela şey fakat gibi ) gibi kelimelerdir

# **---NLP Gerçek Hayat Örneği Yapay Zeka Telefon Bankacılığı Proje**

In [65]:
import pandas as pd
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer

from sklearn.ensemble import RandomForestClassifier

from sklearn.model_selection import train_test_split
# metinsel verilerde veya cümle gibi stacklendiğinde
# önce noktalam işaretleri ile büyük harf olan herşeyi küçük yaparız
#sonrada stop wrodsleri çıkartmamız gerekiyor


In [56]:
 df = pd.read_csv("banka.csv")
 df.head(3)


metin                 kategori
0        kart şifremi değiştirmek istiyorum  Kart Şifresi Değiştirme
1  kartımın şifresini değiştirmek istiyorum  Kart Şifresi Değiştirme
2          kredi kartımın şifresini unuttum  Kart Şifresi Değiştirme

In [55]:
stopwords=['fakat','lakin','ancak','acaba', 'ama', 'aslında', 'az', 'bazı', 'belki', 'biri', 'birkaç', 'birşey', 'biz', 'bu', 'çok', 'çünkü', 'da', 'daha', 'de', 'defa', 'diye', 'eğer', 'en', 'gibi', 'hem', 'hep', 'hepsi', 'her', 'hiç', 'için', 'ile', 'ise', 'kez', 'ki', 'kim', 'mı', 'mu', 'mü', 'nasıl', 'ne', 'neden', 'nerde', 'nerede', 'nereye', 'niçin', 'niye', 'o', 'sanki', 'şey', 'siz', 'şu', 'tüm', 've', 'veya', 'ya', 'yani']

In [60]:
df.head(5)

metin                 kategori
0        kart şifremi değiştirmek istiyorum  Kart Şifresi Değiştirme
1  kartımın şifresini değiştirmek istiyorum  Kart Şifresi Değiştirme
2          kredi kartımın şifresini unuttum  Kart Şifresi Değiştirme
3               kart şifremi hatırlamıyorum  Kart Şifresi Değiştirme
4              kart şifresi almak istiyorum  Kart Şifresi Değiştirme

In [61]:
for word in stopwords:
  word = " " + word + " "
  df["metin"] = df["metin"].str.replace(word," ")

cv = CountVectorizer(max_features=50)

x = cv.fit_transform(df["metin"]).toarray()

y = df["kategori"]

x_train , x_test , y_train , y_test = train_test_split(x , y , random_state = 21 ,train_size = 0.7 )

rf= RandomForestClassifier()
model = rf.fit(x_train , y_train)

model.score(x_test , y_test)