-----------**NUMPY NEDİR ?** ❗❗❗❗


pyhton dosyaları .py ve .ipynb olarak çalışır


In [ ]:
# numpy kütüphanesinin en temel elemanı arraylerdir.

# phythonun diziler komutunun çok boyutlu haline benzer.

#numpy kütüphanesi yüksek oranda c ve c++ ile yazılmıştır.

In [2]:
import numpy as np

In [ ]:
# Arrayler çok boyutlu diziler gibi düşünülebilir.

# Arraylerin boyutları (dimension) vardır. 0d ,1d ,2d ,3d , 4d ....

# Arrayleri oluşturmanıon 3 farjku yolu vardır.

# 1) Liste yada tuple benzeri nesneleri arraye dönüştürebiliriz.        np.array([1,2,3])

# 2) Built_in hazır fonksiyonlra yardımıyla arrayler oluşturabiliriz.   np.arenge() , np.linscape() , np.logspace()

# 3) Rastgele data üreterek                                             np.rando modülünün içindeki fonksiyonlar yardımı ile.

In [ ]:
arr0d = np.array(53)
arr0d

# 0 BOYUTLU BİR ARRAY YAPTIK
# JUPYTER NOTEBOOKLAR EN SON YAZILAN KOMUTU PRİNT ALGILAR

array(53)

In [ ]:
arr1d = np.array([1,2,3,4])
arr1d

# Array'in kaç boyutlu olduğunu anlamak için ([[]]) parantez içindeki köşeli parantez sayısına bakılır

arr2d = np.array([[1,3,5],[2,4,6]])
arr2d

array([[1, 3, 5],
       [2, 4, 6]])

In [ ]:
arr2d[0]

array([1, 3, 5])

In [ ]:
arr3d = np.array([
    [[1, 2, 3], [4, 5, 6]],
    [[7, 8, 9], [10, 11, 12]],
    [[100, 200, 300], [400, 500, 600]]
])

arr3d

array([[[  1,   2,   3],
        [  4,   5,   6]],

       [[  7,   8,   9],
        [ 10,  11,  12]],

       [[100, 200, 300],
        [400, 500, 600]]])

In [ ]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

----- **BUİLT-İN FONKSİYONLAR İLE HIZLICA NUMPY ARRAYLERİ OLUŞTURMA** -----

In [ ]:
# np.arange() fonkisyonu ile hızlıca arrayler oluşturabiliriz . İstediğimiz sayı aralığında ardışık artan arrayler oluştururuz.
# Kullanımı aynı .range() gibi . Start point dahil , End point dahil değil.
# Gene range olduğuğ gibi (start-end-step) olarak görev yapar

In [ ]:
np.arange(0,101,2)

array([  0,   2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,
        26,  28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,
        52,  54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,
        78,  80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

In [ ]:
# np.linspace fonksiyonuyla da hızlıca arrayler oluşturulabilir

np.linspace(30,50,6)
# (başlangıç-son-aralıkta istenilen değer sayısı)
# END POİNT DAHİLDİR

array([30., 34., 38., 42., 46., 50.])

In [ ]:
np.logspace(1,3,7)
# 10 ÜZERİ 1 İLE 10 ÜZERİ 3 ARASINDA 7 ADET SAYI VERDİ

array([  10.        ,   21.5443469 ,   46.41588834,  100.        ,
        215.443469  ,  464.15888336, 1000.        ])

In [ ]:
np.arange(10,101,5)

array([ 10,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60,  65,  70,
        75,  80,  85,  90,  95, 100])

In [ ]:
np.linspace(0,1000,26)

array([   0.,   40.,   80.,  120.,  160.,  200.,  240.,  280.,  320.,
        360.,  400.,  440.,  480.,  520.,  560.,  600.,  640.,  680.,
        720.,  760.,  800.,  840.,  880.,  920.,  960., 1000.])

In [ ]:
np.zeros(5,dtype=int)
# 0 LARDAN ARRAY OLUŞTURUR

array([0, 0, 0, 0, 0])

In [ ]:
np.zeros((3,2) , dtype = int)

array([[0, 0],
       [0, 0],
       [0, 0]])

In [ ]:
np.ones(10,dtype=int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [ ]:
np.ones((3,5),dtype=int) # (1 listesinden kaç adet olcağı,kaç adet 1 olcağı)


array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [ ]:
np.eye(5,dtype = int) # KÖŞEGENDEKİ TÜM DEĞERLER 1 OLCAK ŞEKİLDE GİRİLEN SAYI KADAR YxY LİK BİR KARE VERİR

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [ ]:
np.zeros((2,6),dtype = int)

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [ ]:
# np.random MODÜLÜ İLE RASTGELE ARRAYLER OLUŞTURMA

In [ ]:
np.random.rand(2) # RAND MODÜLÜ 0 - 1 ARASINDA SAYI DÖNDÜRÜR .rand(x) X KADAR DÖNDÜRÜR

array([0.11098648, 0.65230604])

In [ ]:
np.random.rand(4,3) # 1 BOYUTLU İSTENİRSE .rand(X,Y) X = kaç tane liste olcağı  Y = listede kaç eleman olucağu

array([[0.81302046, 0.96630641, 0.76165874],
       [0.98430816, 0.69704748, 0.83639652],
       [0.24696474, 0.19965417, 0.20411409],
       [0.61719376, 0.78716693, 0.16655907]])

In [ ]:
np.random.randint(15,50,5) # .randint(x,y,z) X = Alt sınır , Y = Üst sınır Z = Aralıktan kaç eleman istendiği

array([26, 36, 23, 36, 15])

In [ ]:
np.random.randint(15,50,(3,5)) # SONDAKİ PARANTEZ YİNE AYNI İLK ELEMAN KAÇ LİSTE OLCAĞI 2. ELEMEN KAÇ TANE ELEMAN OLCAĞI

array([[24, 31, 20, 41, 40],
       [28, 41, 39, 23, 20],
       [17, 21, 31, 32, 32]])

In [ ]:
np.random.randint(0,50,(4,6))

array([[ 4, 45,  2, 27,  3, 40],
       [18, 19,  6, 35, 43, 33],
       [27, 28,  8, 45, 21, 42],
       [ 2, 19, 46, 44, 40, 31]])

---- ARRAYİN BOYUT SAYISINI VE SHAPE İNİ KONTROL ETMEK -----

In [ ]:
# .ndim attrşbute ı ile arrayimizin kaç boyutlu olduğunu öğrenebiliriz

In [ ]:
arr2d.ndim

2

In [ ]:
# .shape attribute ı ile arraying shapeine bakılabilir
arr2d.shape
# bir nevi kaç satır ve sütun olduğunu döndürür

(2, 3)

---- NUMPY ARRAYLERİNİ İNDEKSLEME VE ÖGELERİME ERİŞME

In [ ]:
arr1d # 1 boyutlu arrayler aynı listeler gibidir.

In [ ]:
arr1d[0]

np.int64(1)

In [ ]:
arr2d[0]

array([1, 3, 5])

In [ ]:
arr2d[0][0]

np.int64(1)

In [ ]:
arr3d[1][1][1]

np.int64(11)

---- NUMPY DİZİLERİNİN MAX - MİN ELEMANLARINA VE BU ELEMAN İNDEXLERİNE ERİŞME


In [3]:
arr = np.random.randint(1,100,10)
arr

array([59, 14, 70, 45, 80,  3, 66, 72, 34, 65])

In [4]:
arr.max() / arr.min()

np.int64(80)

In [5]:
arr.argmax() /// arr.argmin()

np.int64(4)


------- NUMPY ARRAYLERİNDE SLİCİNG(DİLİMLEME) YAPILABİLİR


In [9]:
arr= np.arange(50,65)
arr

array([50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64])

In [10]:
arr[-5:]

array([60, 61, 62, 63, 64])

In [11]:
arr[5:11]

array([55, 56, 57, 58, 59, 60])

In [12]:
arr[5:11] = 789
arr

array([ 50,  51,  52,  53,  54, 789, 789, 789, 789, 789, 789,  61,  62,
        63,  64])

---- ARRAYİNG VERİ TÜRÜNÜ (DATA TYPE I) KONTROL ETME

In [ ]:
#.dtype ile kontrol edilir

In [13]:
arr.dtype

dtype('int64')

In [14]:
arr = np.array(["a","b","c"])
arr.dtype

dtype('<U1')

---- ARRAYİN D TYPE INI DEĞİŞTİRME

In [15]:
arr = np.array([1.2,3.5,5.8])
arr

array([1.2, 3.5, 5.8])

In [ ]:
# .astype ile arraylerin dtype ı değiştirilebilir

In [16]:
arr.astype(int)

array([1, 3, 5])