

**BİR ARRAYİN SHAPEİNİ KONTROL ETME**



In [ ]:
# .shape  kullanılır
# bir arrayin shape i her boyuttaki ögelerinin sayısına eşittir

In [1]:
import numpy as np

In [ ]:
arr2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
arr2d.shape

(3, 3)

In [ ]:
arr3d = np.array([[[1,2,3],[4,5,6]] , [[10,20,30],[5,10,20]]])
arr3d.shape

(2, 2, 3)

---- BİR ARRAYİ RE-SHAPE ETME

In [ ]:
# .reshape methodunda toplam eleman sabit tutmaya dikkat edilmeli.

# .arrange ile oluşturulan arrayler tek boyutlu bu yüzden .shape baya kullanılır.

In [ ]:
new_arr2d = arr3d.reshape(6,2)
new_arr2d

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [10, 20],
       [30,  5],
       [10, 20]])

In [ ]:
new_arr = np.arange(0,100,5)
new_arr.reshape(2,2,5)

array([[[ 0,  5, 10, 15, 20],
        [25, 30, 35, 40, 45]],

       [[50, 55, 60, 65, 70],
        [75, 80, 85, 90, 95]]])

----- BİİLNMEYEN BOYUT

In [ ]:
# .reshape() methodu kullanılırken hesaplamak istemediğimiz boyut yerine -1 yazıp otomatik hesaplatabiliriz.

In [ ]:
# mesela 120 elemanlı array i 3 boyutlu yapmak için (10,2,-1) yazınca -1 kendini bilinmeyen x gibi alır ve gerekli çarpımı hesaplar yani 6 burdaki örnekte.

-----ARRAYLERİ DÜZLEME (FLATTEN)

In [ ]:
# Çok boyutlu bir arrayi tek boyutlu haline getirme
# basitçe .reshape(-1) komutu ile yapılır

In [ ]:
arr2d = np.arange(40).reshape(4,10)
arr2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]])

In [ ]:
arr2d.reshape(-1)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39])

---- ÇOK BOYUTLU ARRAYLERDE ITERATİON(YİNELEME)

In [ ]:
arr2d = np.arange(20).reshape(4,5)

In [ ]:
for x in arr2d:
  print(x)

[0 1 2 3 4 5 6 7 8 9]
[10 11 12 13 14 15 16 17 18 19]
[20 21 22 23 24 25 26 27 28 29]
[30 31 32 33 34 35 36 37 38 39]


In [ ]:
# for x in arr2d:
#   for y in x:
#     print(y)
#FOR ÇOK KULLANIİŞSSIZDIR

In [ ]:
# ÇOK BOYUTLU ARRAYLERDE .nditer() fonksiyonu bunun için geliştirilmiştir

In [ ]:
for x in np.nditer(arr3d):
  print(x)

1
2
3
4
5
6
10
20
30
5
10
20


----ARRAY ELEMANLARI ARASINDA 4 İŞLEM

In [ ]:
arr1 = np.array([10,20,50,100])
arr2 = np.array([5,7,9,-1])

In [ ]:
arr1 + arr2

array([15, 27, 59, 99])

----ARRAYİN TOPLAM ORTALAMA VARYANSINA STANDART SAPMASINA BAKMA

In [ ]:
arr = np.random.randint(0,10,10)
arr

array([0, 2, 9, 9, 1, 1, 1, 3, 6, 4])

In [ ]:
arr.sum()

np.int64(36)

In [ ]:
arr.mean()

np.float64(3.6)

In [ ]:
arr.var()

np.float64(10.040000000000001)

In [ ]:
arr.std()

np.float64(3.168595903550972)

In [ ]:
np.sqrt(arr) HER ELEMANIN KAREKÖKÜ

array([0.        , 1.41421356, 3.        , 3.        , 1.        ,
       1.        , 1.        , 1.73205081, 2.44948974, 2.        ])

----NUMPY ARRAYLERİNİ BİRLEŞTİRME

In [ ]:
# np.concatenate([],[],axis=1)

In [2]:
arr1= np.array([10,20,30,70])

arr2 = np.array([100,200,600,900])

In [3]:
np.concatenate([arr1,arr2],axis=0)

array([ 10,  20,  30,  70, 100, 200, 600, 900])

In [ ]:
# ARRAYLERİS TACKLEME (YIĞINLAMA)
# yeni bir boyut eklenir 2 boytulunun 3 olması gibi

In [4]:
arr1 =np.array([[1,2,3],[4,5,6]])
arr2 =np.array([[100,200,300],[700,800,900]])

In [5]:
np.stack([arr1,arr2],axis=0)

array([[[  1,   2,   3],
        [  4,   5,   6]],

       [[100, 200, 300],
        [700, 800, 900]]])

**----   NUMPY ARRAYLERİNDE İNDEXLE ARAMA**

In [ ]:
# aradığımız değerlerin bulunduğu indexleri döndürmek içi np.where kullanılır

#np.where() içine şart alır

In [6]:
arr = np.array([1,2,5,6,7,7,9,2,2,2])
np.where(arr == 9)

(array([6]),)

In [9]:
np.where(arr == 2)

(array([1, 7, 8, 9]),)

In [10]:
np.where(arr%2 !=0)

(array([0, 2, 4, 5, 6]),)

In [ ]:
# numpy random kütüphanesi

In [11]:
np.random.choice(arr)

np.int64(2)

In [13]:
np.random.choice([10,20,30,40])

np.int64(10)